name: self-hosted test

on:
  push:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - run: pip install -r requirements.txt

    - run: pip install flake8 bandit pyright

    - run: flake8 occameracontrol

    - run: bandit -r occameracontrol

    - run: pyright occameracontrol
